apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: development
namePrefix: dev-
nameSuffix: -env

resources:
- ../../base

replicas:
- count: 4
  name: nginx001

images:
- newName: kiran2361993/kubegame
  newTag: v2
  name: kiran2361993/kubegame
