apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx001
  name: nginx001
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx001
  template:
    metadata:
      labels:
        app: nginx001
    spec:
      containers:
      - image: kiran2361993/kubegame:v2
        name: appcontainer



