apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ./service.yaml
  - ./deployment.yaml
  - ./rbac.yaml

labels:
  - pairs:
      role: monitoring
      owner: java-appteam
      environment: production
      batch: saikiranpi
    includeSelectors: false

images:
- name: xxx.dkr.ecr.eu-central-1.amazonaws.com/container1
  newTag: "1111"

